name: Terraform Pipeline

on:
  push:

jobs:
  tf-run:
    name: Terraform Run
    runs-on: ubuntu-latest

    steps:
      - name: Step 01 - Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Step 02 - Terraform Version
        run: terraform --version
